version: "3"
services:
  app:
    image: badi
    container_name: CDTA-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - CDTA

  db:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: sdproject
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: cdta_user
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

    networks:
      - CDTA
  nginx:
    image: nginx:alpine
    container_name: CDTA-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - CDTA

networks:
  CDTA:
    driver: bridge
